baseURL = "https://clawacq.github.io/"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "老许的博客"
theme = "PaperMod"
defaultContentLanguage = "zh"

[params]
  label = { text = "老许", icon = "" }
  description = "安全研究 | 技术笔记 | 生活随想"
  author = "老许"
  # no search for now
  disableSearch = true

[build]
  writeStats = true
